/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nibasabin' at '5/31/17 4:38 PM' with Gradle 2.14
 *
 * @author nibasabin, @date 5/31/17 4:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
